{% set version = "2.3.2" %}

package:
  name: distributed
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/d/distributed/distributed-{{ version }}.tar.gz
  sha256: 8e85a93f6f96b2598b29fbe6b34233001ea30b9cc2dfbd6459146f9c289a0d88

build:
  number: 0
  entry_points:
    - dask-scheduler=distributed.cli.dask_scheduler:go
    - dask-ssh=distributed.cli.dask_ssh:go
    - dask-worker=distributed.cli.dask_worker:go
    - dask-remote=distributed.cli.dask_remote:go
    - dask-submit=distributed.cli.dask_submit:go
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  noarch: python

requirements:
  host:
    - python >=3.5
    - pip

  run:
    - python >=3.5
    - click >=6.6
    - cloudpickle >=0.2.2
    - cytoolz >=0.7.4
    - dask-core >=2
    - msgpack-python
    - psutil >=5.0
    - pyyaml
    - six
    - sortedcontainers !=2.0.0,!=2.0.1
    - tblib
    - toolz >=0.7.4
    - tornado >=5
    - zict >=0.1.3

test:
  imports:
    - distributed
    - distributed.cli
    - distributed.comm
    - distributed.deploy
    - distributed.diagnostics
    - distributed.protocol
  commands:
    - dask-scheduler --help
    - dask-ssh --help
    - dask-worker --help

about:
  home: http://distributed.readthedocs.io/en/latest/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: 'Distributed computing with Dask'
  description: |
    Distributed is a lightweight library for distributed computing in Python.
    It extends both the concurrent.futures and dask APIs to moderate sized
    clusters.
  doc_url: https://distributed.dask.org
  doc_source_url: https://github.com/dask/distributed/blob/master/docs/source/index.rst
  dev_url: https://github.com/dask/distributed

extra:
  recipe-maintainers:
    - mrocklin
    - pitrou
    - jcrist
    - martindurant
    - jakirkham
    - marcelotrevisani
    - ogrisel
    - tomaugspurger
    - jrbourbeau
